### PR TITLE
Add UniversalViewer

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:red_circle:

**Comment by cbeer** [comment]
Yikes. I wonder if there's value in pulling out the assets into a `universalviewer-rails` gem?

**Comment by jcoyne** [comment]
@cbeer Part of the difficulty of that would be that UV dynamically loads code, so I don't think it can be compiled in the asset pipeline.  This is something that @tpendragon ran into in Plum.

**Comment by mjgiarlo** [comment]
Egads. Do we still need hound in the mix on hybox?

**Comment by tpendragon** [comment]
You'd have to do it in an engine, which would be a lot of breaking up UV. If you can do it though, I'd totally use it!

**Comment by mjgiarlo** [comment]
We discussed this PR in today's HyBox/Sufia standup and decided to merge it so that we can include the UV in our demos in Dublin. This is ripe for extraction to a new engine, and it could possibly be taken up this summer.

**Pull request merged**
