### PR TITLE
Use locally generated sufia css

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
This CSS is from upstream; we haven't done anything to customize hound's CSS behavior, and I'm not inclined to that here.

**Comment by mjgiarlo** [comment]
@cbeer Rebase, pls.

**Comment by mjgiarlo** [comment]
This PR means that if Sufia makes CSS changes in the future, we won't automatically pick that up (because it's not generated into our app)? I believe this change is consistent with the work you've been doing -- just confirming.

Thoughts on this, @jcoyne @atz?

**Comment by cbeer** [comment]
Right; if Sufia makes changes to the upstream `sufia.scss` file that it generates into our app, we won't automatically pick it up. This file just sets up some dependencies, so it should be relatively static.

If Sufia makes changes within `app/assets/sufia/sufia.scss`, we'll always get it as normal.

**Comment by mjgiarlo** [comment]
:ok_hand:

**Pull request merged**
