### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by jcoyne** [comment]
Currently Hydra-works is reporting that every file is a virus unless ClamAV is installed.  Do we want to wait until that is resolved?

**Comment by atz** [comment]
Rebase needed in any case.

**Comment by mjgiarlo** [comment]
Fixed in HW: https://github.com/projecthydra-labs/hydra-works/pull/297

**Comment by atz** [comment]
Rebased, waiting for CI.

**Comment by atz** [comment]
CI fails with:
```
app/services/sufia/actor_factory.rb:2:in `<module:Sufia>': uninitialized constant CurationConcerns::Actors (NameError)
```

**Comment by cbeer** [comment]
Did we lose something in the `Gemfile.lock`? I thought that was introduced in `curation_concerns 1.0.0.beta2 `

**Comment by cbeer** [comment]
Yeah -- there's a /ton/ of dependencies I have in my local branch that are missing here.

**Comment by cbeer** [comment]
Pushed with my changes.

**Comment by atz** [comment]
I have reproduced the failing test locally.  Not sure what is related.

**Pull request merged**
