### PR TITLE
Extract Tab class from StatisticsTabManager

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
suggestions for refactoring #241

**Comment by jcoyne** [comment]
But some tabs are going to have multiple graphs. When my Sufia PR is merged I'll add works by type graph to the works tab.

**Comment by jcoyne** [comment]
I now have two graphs on the Works tab in #241

**Comment by cbeer** [comment]
Ok, rebased with that, and ended up making the graphs declarative in `admin/stats/index.html.erb`.

**Comment by jcoyne** [comment]
This is great! Thanks @cbeer

**Comment by mjgiarlo** [comment]
:clap:

**Pull request merged**
