### PR TITLE
Remove stale sidekiq reference from README

### PR DESCRIPTION
**Pull request by mjgiarlo**
And re-order import sections.

### CODE REVIEW

**Comment by jcoyne** [comment]
Do you want to remove `peek-sidekiq` too?

**Comment by mjgiarlo** [comment]
I worked this up via the website editor. If you'd like me to more fully strip out sidekiq, I can do so, but probably not 'til tomorrow.

OTOH, I might like to have sidekiq available for local installs, but that's a can of worms we have yet to open. Perhaps let's hold on fully removing sidekiq for now, and just clean up the README?

**Comment by mjgiarlo** [comment]
Rebased.

**Comment by jcoyne** [comment]
Rebase and I'll merge.

**Comment by mjgiarlo** [comment]
@jcoyne done-zo

**Pull request merged**
